### ISSUE TITLE
conda selects wrong openblas build

### ISSUE THREAD

**Issue by stuarteberg** [conda-forge/coincbc-feedstock#15]
OK, so I could use a little advice here.  Our latest build of `coincbc` requires `openblas-0.2.19-2`.  (Build `0.2.19-1` will not suffice, due to the different `dylib` name as I mentioned in #14.)

Yet when I attempt to install `coincbc` it to a fresh environment, it seems to prefer build `1` (from `defaults`) instead of build `2` (from `conda-forge`):

```
$ conda --version
conda 4.3.22

$ conda create -n delme coincbc=2.9.9=blas_openblas_0
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /miniforge/envs/delme:

The following NEW packages will be INSTALLED:

    blas:        1.1-openblas          conda-forge
    coincbc:     2.9.9-blas_openblas_0 conda-forge [blas_openblas]
    lapack:      3.6.1-1               conda-forge
    libgcc:      4.8.5-1
    libgfortran: 3.0.0-1
    openblas:    0.2.19-1

Proceed ([y]/n)? n

Exiting
```

As shown below, I can force the solver to select the correct build of `openblas` by adding it to the install specs, but why should I have to?  (BTW, `conda-forge` is, of course, listed before `defaults` in my `.condarc` file.)

```
$ conda create -n delme coincbc=2.9.9=blas_openblas_0 openblas=0.2.19=2
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /miniforge/envs/delme:

The following NEW packages will be INSTALLED:

    blas:        1.1-openblas          conda-forge
    coincbc:     2.9.9-blas_openblas_0 conda-forge [blas_openblas]
    lapack:      3.6.1-1               conda-forge
    libgcc:      4.8.5-1
    libgfortran: 3.0.0-1
    openblas:    0.2.19-2              conda-forge

Proceed ([y]/n)? n

Exiting
```

This problem is preventing me from building a different recipe (`lemon`).  One option would be to edit the `coincbc` recipe to explicitly pin the `openblas` build string:

```yaml
requirements:
  build:
    - toolchain
    - gcc
    - blas 1.1 {{ variant }}
    - openblas 0.2.19 2 # Require build 2!
    - lapack
  run:
    - libgcc
    - blas 1.1 {{ variant }}
    - openblas 0.2.19 2 # Require build 2!
    - lapack

```

...but that seems strange.  Any ideas?
